// Arthur: NarIyirm
// 中文：判分只来自固定材质题库；null 表示地方服务差异，仅提供指引，AI 不决定正确桶。
// EN: Fixed material rules grade lessons; null means local variation and guidance only, so AI never decides the correct bin.
export const WASTE_MATERIALS = {
  eggshell: { zh: '鸡蛋壳', en: 'Eggshell', stream: 'organics', emoji: '🥚', subject: 'two pieces of empty cracked eggshell', reasonZh: '蛋壳是有机残余物。当地接受厨余的 FOGO 服务或合适的堆肥方式可处理；实际投放请查当地指引。', reasonEn: 'Eggshell is organic residue. Use FOGO only where accepted, or follow suitable composting guidance.' },
  organic_residue: { zh: '果皮／天然残余物', en: 'Peels / natural residue', stream: 'organics', emoji: '🍌', subject: 'a discarded banana peel', reasonZh: '天然果皮和残余物属于有机材料。当地 FOGO 接收范围和家庭堆肥适用范围可能不同。', reasonEn: 'Natural peels and residue are organic material. Local FOGO and home composting acceptance may differ.' },
  aluminium_can: { zh: '空铝罐', en: 'Empty aluminium can', stream: 'recycling', emoji: '🥫', subject: 'an empty slightly crushed unbranded aluminium beverage can', reasonZh: '倒空的铝饮料罐属于可回收金属包装；符合条件的罐也可通过容器退费计划处理。', reasonEn: 'Empty aluminium drink cans are recyclable metal packaging. Eligible cans can also use container deposit schemes.' },
  plastic_bottle: { zh: '空塑料瓶', en: 'Empty plastic bottle', stream: 'recycling', emoji: '🧴', subject: 'an empty clear plastic beverage bottle without a label', reasonZh: '倒空的硬塑料饮料瓶通常属于可回收包装。瓶盖是否分开、清洁要求和收集方式请查当地指引。', reasonEn: 'Empty rigid plastic drink bottles are commonly recyclable. Check local instructions for lids, preparation and collection.' },
  glass_container: { zh: '玻璃瓶／罐', en: 'Glass bottle / jar', stream: null, emoji: '🍾', subject: 'an empty unbranded clear glass food jar', reasonZh: '食品玻璃瓶和罐可回收，但维州部分地区使用独立玻璃收集服务，不能统一指定黄色桶。查看当地玻璃投放指引；饮水杯、陶瓷和耐热玻璃不属于此类。', reasonEn: 'Food glass bottles and jars are recyclable, but parts of Victoria use separate glass collection. Check your local glass service; drinking glasses, ceramics and heat-resistant glass are different materials.' },
  paper_cardboard: { zh: '干净纸／纸盒', en: 'Clean paper / cardboard', stream: 'recycling', emoji: '📦', subject: 'an empty plain uncoated cardboard food box folded flat', reasonZh: '干净、干燥且无复合涂层的纸和纸板通常可回收。沾油、覆膜或复合材质需另查当地规则。', reasonEn: 'Clean, dry uncoated paper and cardboard are commonly recyclable. Greasy, laminated or composite packaging needs separate local guidance.' },
  rigid_plastic: { zh: '硬塑料盒／托盘', en: 'Rigid plastic tub / tray', stream: null, emoji: '📦', subject: 'an empty unbranded rigid plastic food tray', reasonZh: '硬塑料盒和托盘的接收范围取决于材质及当地服务。查看包装的 Australasian Recycling Label 和当地 council 指引。', reasonEn: 'Acceptance of rigid plastic tubs and trays depends on the material and local service. Check the Australasian Recycling Label and your council.' },
  soft_plastic: { zh: '软塑料袋／薄膜', en: 'Soft plastic bag / film', stream: null, emoji: '🛍️', subject: 'an empty crumpled transparent soft plastic packaging bag', reasonZh: '软塑料袋和薄膜不能直接按硬塑料瓶分类。请查包装标签和当地是否提供专门收集服务。', reasonEn: 'Soft bags and film are different from rigid bottles. Check the packaging label and whether your area offers a dedicated collection service.' },
  carton: { zh: '复合饮料纸盒', en: 'Composite drink carton', stream: null, emoji: '🧃', subject: 'an empty unbranded folded beverage carton', reasonZh: '饮料纸盒可能含纸、塑料和铝复合层，各地接收规则不同。请按包装标签和当地指引处理。', reasonEn: 'Drink cartons can combine paper, plastic and aluminium. Acceptance varies; follow the packaging label and local guidance.' },
  other: { zh: '其他丢弃物', en: 'Other waste', stream: null, emoji: '📦', subject: 'an empty plain mixed material food package', reasonZh: '这类丢弃物尚无可靠的通用答案。确认具体材料，并查看包装标签和当地分类服务。', reasonEn: 'There is no reliable universal answer for this item. Identify the material and check its label and local collection service.' },
  unknown: { zh: '材质待确认', en: 'Material unknown', stream: null, emoji: '❓', subject: null, reasonZh: '暂时不能确定材料。可以在库存编辑中补充包装信息，再按当地指引处理。', reasonEn: 'The material is not confirmed. Add packaging details in inventory editing and check local disposal guidance.' },
};

